version: "2"
services:

    mongo:
      image: mongo
      container_name: ucp-mongodb

    nodejs:
      build: build/nodejs
      restart: always
      container_name: ucp-nodejs
      working_dir: /application/src/api
      volumes:
        - .:/application
      ports:
        - "3001:3001"
      links:
        - mongo
      depends_on:
        - mongo

    python:
      build: build/machine-learning
      container_name: ucp-machine-learning
      working_dir: /application/src/ml
      entrypoint:
        - flask
        - run
        - --host=0.0.0.0
      environment:
        FLASK_DEBUG: 1
        FLASK_APP: ./app.py
      ports: ['5000:5000']
      volumes:
        - .:/application
      links:
        - mongo
      depends_on:
        - mongo

    webserver:
      image: nginx:alpine
      container_name: ucp-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      depends_on:
       - nodejs

